const hero = {
  walka: 1,
  parkour: 1,
  krzepa: 1,
  charyzma: 1,
  zimna: 1,
  status: 1,
  okultyzm: 1,
  wiedza: 1,
  czujnosc: 1,
  witalnosc: 0,
  ciosu: 0,
  pancerz: 0,
  wola: 0,
  presja: 0,
  mistyczny: 0,
  drzewo: 4,
  zasoby: 0,
  rodzina: '',
  osiągnięcia: '',
  ciemność: {},
  bonus: 0,
  tempBonus: 0,
  hisClan: { name: 'Przyszedł bosy' },
  hisTour: { name: 'Poszedłw butach' },
  hisSecr: { name: 'Bo ukradł' },
  openTree: 0,
  przewagi: 0,
  splugawienie: 0,
  ekstraTalent: 0,
  ekstraSprzet: 0,
  experience: { chosen1: 0, chosen2: 0, chosen3: 0, },
  archetype: '',
  numberOfMaterialsToChoose: 0,
  chosenMaterials: {},
  addedSkills: {},
  addedSkillCount: {
    1: 3,
    2: 2,
  },
  sex: '',
  name: '',
  clanName: '',
};
const tempHero = {
  
}
//spis umiejętności dla poszczególnych frakcji
const fraction = {
  soldaci:
  {
    walka: 1,
    parkour: 1,
    charyzma: 1,
    status: 1,
    okultyzm: 1,
    czujnosc: 1,
    witalnosc: 3,
    wola: 1,
  },
  hanza:
  {
    walka: 1,
    krzepa: 1,
    charyzma: 1,
    zimna: 1,
    status: 2,
    witalnosc: 2,
    wola: 2,
  },
  mechanisci:
  {
    parkour: 1,
    krzepa: 1,
    zimna: 1,
    status: 1,
    wiedza: 1,
    czujnosc: 1,
    witalnosc: 2,
    wola: 2,
  },
  rytualisci:
  {
    walka: 1,
    parkour: 1,
    zimna: 1,
    status: 1,
    okultyzm: 1,
    wiedza: 1,
    witalnosc: 1,
    wola: 3,
  }
};
//Obiekt z dostosowanym treścią wszystkich historycznych wydarzeń, wyciąge się je przy pomocy obiektu {history}
const historyTable = {
  clan: {
    "Beztroskie dzieciństwo": {
      name: "Beztroskie dzieciństwo",
      opis: "Nasz klan żył w dostatku i pokoju, miałem kochających rodziców i przyjaznych  sąsiadów.",
      give: { drzewo: 1, witalnosc: 1 }
    },
    "Wojna": {
      name: "Wojna",
      opis: "Klan przez długie lata prowadził działania wojenne przeciw najbliższym sąsiadom.",
      give: { walka: 1, okultyzm: 1 }
    },

    "Objawienie artysty": {
      name: "Objawienie artysty",
      opis: "Odkryłem w sobie duszę artystyczną i postanowiłem tworzyć.",
      give: { drzewo: 1, wola: 1 }
    },
    "Oskarżenia o herezję": {
      name: "Oskarżenia o herezję",
      opis: "Każdy z klanu był podejrzany, a po roku śledztwa ogłoszono zaskakujące decyzje.",
      give: { czujnosc: 1, 'zimna': 1 }
    },
    "Upiór": {
      name: "Upiór",
      opis: "Wysłannik Czarnej spirali zamieszkał wśród nas. Wielu z nas zginęło zanim udało nam się wygnać go z klanu.",
      give: { wola: 1, mistyczny: 1 }
    },
    "Eksperymenty alchemiczne": {
      name: "Eksperymenty alchemiczne",
      opis: "Receptury nie były precyzyjne  	i musiałem testować je na sobie.",
      give: { krzepa: 1, okultyzm: 1 }
    },
    "Weryfikacja umów": {
      name: "Weryfikacja umów",
      opis: "Pracując przy analizie dokumentów handlowych nauczyłem się zwracać uwagę na najdrobniejsze szczegóły.",
      give: { czujnosc: 1, wiedza: 1 }
    },
    "Porywczy przełożony": {
      name: "Porywczy przełożony",
      opis: "Musiałem uważać na każde słowo, aby nie sprowokować wybuchu dzikiej furii.",
      give: { parkour: 1, zimna: 1 }
    },
    "Bestia w ludzkiej skórze": {
      name: "Bestia w ludzkiej skórze",
      opis: "Seria mordów wstrząsnęły klanem. Znalazłem i powstrzymałem zwyrodnialca.",
      give: { walka: 1, wiedza: 1 }
    },
    "Przesłuchanie": {
      name: "Przesłuchanie",
      opis: "Miesiącami starałem się wydobyć kluczową informację od pojmanego jeńca.",
      give: { charyzma: 1, krzepa: 1 }
    },
    "Rytuał traw": {
      name: "Rytuał traw",
      opis: "Miałem okazję wziąć udział w tajemniczym rytuale, który zmienił mnie na zawsze.",
      give: { mistyczny: 1, okultyzm: 1 }
    },
    "Szkoła": {
      name: "Szkoła",
      opis: "Pobierałem nauki w większym ośrodku klanowym. Był to czas nauki, zabawy i zawierania znajomości.",
      give: { wiedza: 1, okultyzm: 1 }
    },
    "Zawody": {
      name: "Zawody",
      opis: "Brałem udział w klanowych rozgrywkach sportowych.",
      give: { parkour: 1, status: 1 }
    },
    "Twarde negocjacje": {
      name: "Twarde negocjacje",
      opis: "Stoczyłem ciężki dyplomatyczny bój z przebiegłym  przeciwnikiem.",
      give: { charyzma: 1, wiedza: 1 }
    },
    "Pomocnik medyka": {
      name: "Pomocnik medyka",
      opis: "Pomagałem klanowemu lekarzowi przyrządzać maści i wywary.",
      give: { krzepa: 1, wiedza: 1 }
    },
    "Zakapiory": {
      name: "Zakapiory",
      opis: "Stać mnie było dawniej na srogich rębajłów. Wielu do dziś  pamięta, że lepiej ze mną nie zaczynać.",
      give: { zimna: 1, status: 1 }
    },
    "Zdrada": {
      name: "Zdrada",
      opis: "Gdy przyjaciel zdradził, musiałem zaufać intuicji i działać bez zastanowienia.",
      give: { parkour: 1, czujnosc: 1 }
    },
    "Uczeń czarnoksiężnika": {
      name: "Uczeń czarnoksiężnika",
      opis: "Był prawdziwym mędrcem, to był zaszczyt mieć takiego mentora.",
      give: { status: 1, okultyzm: 1 }
    },
    "Pojedynek": {
      name: "Pojedynek",
      opis: "Zwieńczeniem długotrwałego konfliktu był pojedynek, po którym wyniosłem tę bliznę przy oku.",
      give: { walka: 1, charyzma: 1 }
    },
    "Mistrz ostrza": {
      name: "Mistrz ostrza",
      opis: "Szkolił mnie jeden z legendarnych mistrzów walki, który zamieszkał u nas w klanie.",
      give: { walka: 1, status: 1 }
    },
    "Na szczycie władzy": {
      name: "Na szczycie władzy",
      opis: "Posiadałem silną pozycję, po której pozostały mi znajomości oraz nawyki wydawania poleceń.",
      give: { charyzma: 1, status: 1 }
    }
  },
  tour: {
    "W warsztacie Mechanistów": {
      name: "W warsztacie Mechanistów",
      opis: "Pracowałem nad tajemnym projektem konstruktorów Gildii Mechanistów..",
      give: { wiedza: 1, bonus: 1 }
    },
    "Krwawa potyczka": {
      name: "Krwawa potyczka",
      opis: "Nie było czasu na odwrót, musiałem bronić swego życia.",
      give: { walka: 1, czujnosc: 1 }
    },
    "Herezja u sąsiadów": {
      name: "Herezja u sąsiadów",
      opis: "Zostałem wcielony przez inkwizytora do grupy śledczej, by zdemaskować kult w sąsiednim klanie.",
      give: { charyzma: 1, okultyzm: 1 }
    },
    "Podniebna bitwa": {
      name: "Podniebna bitwa",
      opis: "Stoczyłem powietrzną bitwę na pokładzie latającego okrętu.",
      give: { walka: 1, 'zimna': 1 }
    },
    "Cmentarzysko maszyn": {
      name: "Cmentarzysko maszyn",
      opis: "W poszukiwaniu Żaru odwiedziłem ruiny czcicieli maszyn.",
      give: { parkour: 1, wiedza: 1 }
    },
    "Egzorcyzmy": {
      name: "Egzorcyzmy",
      opis: "Towarzyszyłem najlepszym zaklinaczom justycjariusza w pochwyceniu potężnego upiora.",
      give: { czujnosc: 1, okultyzm: 1 }
    },
    "Wyprawa po wierzchowce": {
      name: "Wyprawa po wierzchowce",
      opis: "Pojmanie bestii z gniazda matki to nie przelewki.",
      give: { krzepa: 1, zimna: 1 }
    },
    "Oblężenie": {
      name: "Oblężenie",
      opis: "Gdy szturmy zawiodły, zdobyliśmy fortecę wroga podstępem.",
      give: { charyzma: 1, zimna: 1 }
    },
    "Odpowiedzialne zadanie": {
      name: "Odpowiedzialne zadanie",
      opis: "Jako dowódca grupy zadaniowej odpowiadałem za powodzenie akcji.",
      give: { charyzma: 1, czujnosc: 1 }
    },
    "Oczyścić teren": {
      name: "Oczyścić teren",
      opis: "Zadanie było proste, wytępić przeklęte bestie z terytorium unitów.",
      give: { witalnosc: 1, czujnosc: 1 }
    },
    "Wyprawa do gniazda": {
      name: "Wyprawa do gniazda",
      opis: "Przeniknąłem do jednego z przeklętych gniazd Hurmy.",
      give: { krzepa: 1, czujnosc: 1 }
    },
    "Obława na splugawionych": {
      name: "Obława na splugawionych",
      opis: "Tropienie splugawionych, były większą przygodą niż konfrontacja.",
      give: { parkour: 1, okultyzm: 1 }
    },
    "Szkolenie szturmowców": {
      name: "Szkolenie szturmowców",
      opis: "Przebywałem wśród elitarnego ciężkozbrojnego oddziału Mechanistów.",
      give: { krzepa: 1, wiedza: 1 }
    },
    "Na dworze seniora": {
      name: "Na dworze seniora",
      opis: "Byłem gościem hanzyckiego arystokraty i poznałem wielu jego lenników.",
      give: { status: 1, wiedza: 1 }
    },
    "Wypad do katedry": {
      name: "Wypad do katedry",
      opis: "Szabrowanie w świątyni Cesarza uczy szybko przebierać nogami.",
      give: { zimna: 1, okultyzm: 1 }
    },
    "Żarowy przemyt": {
      name: "Żarowy przemyt",
      opis: "Przez pewien czas zajmowałem się zdobywaniem i sprzedażą Żaru ze starożytnych ruin.",
      give: { parkour: 1, charyzma: 1 }
    },
    "Ucieczka z kazamatów": {
      name: "Ucieczka z kazamatów",
      opis: "Głębokie tunele, zalany kanał, a na plecach strażnicy i ich wściekłe ogary.",
      give: { parkour: 1, krzepa: 1 }
    },
    "Pokrewna dusza": {
      name: "Pokrewna dusza",
      opis: "W czasie podróży poznałem wpływowego mistyka ze stolicy i zaprzyjaźniliśmy się.",
      give: { status: 1, okultyzm: 1 }
    },
    "Krwawe łowy": {
      name: "Krwawe łowy",
      opis: "Z grupą Rytualistów brałem udział w polowaniu na potężnego demona.",
      give: { walka: 1, mistyczny: 1 }
    },
    "Nauki u szalonego konstruktora": {
      name: "Nauki u szalonego konstruktora",
      opis: "Pobierałem nauki u prawdziwego technicznego wizjonera.",
      give: { zimna: 1, wiedza: 1 }
    },
    "Piekło na ziemi": {
      name: "Piekło na ziemi",
      opis: "Wojenna wyprawa z Soldatami obnażyła to, co każdy nosił w sercu.",
      give: { walka: 1, parkour: 1 }
    }
  },
  secr: {
    "Przed obliczem justycjariusza": {
      name: "Przed obliczem justycjariusza",
      opis: "Oskarżenia, świadkowie, plotki i groźba tortur.",
      give: { drzewo: 1 }
    },
    "Pakt ze splugawionym": {
      name: "Pakt ze splugawionym",
      opis: "Spotkałem splugawionego, z którym rozpocząłem bardzo ryzykowną grę...",
      give: { osiągnięcia: "Potężny splugawiony (Status 6) jest ci winny Przysługę.</br>" }
    },
    "W kajdanach": {
      name: "W kajdanach",
      opis: "Każdego dnia oprawcy próbowali mnie złamać, a wieczory wypełniałem marzeniami o ucieczce.",
      give: { witalnosc: 1 }
    },
    "Jedyny ocalały": {
      name: "Jedyny ocalały",
      opis: "Mój klan naraził się potężnemu wrogowi i został zrównany z ziemią. Tylko ja przeżyłem.",
      give: { ekstraTalent: 1 } //@TODO ekstratalent do dorobienia
    },
    "Wielki przekręt": {
      name: "Wielki przekręt",
      opis: "Wziąłem udział w zuchwałym oszustwie. Jeszcze kilka lat muszę trzymać język za zębami.",
      give: { status: 1 }
    },
    "Objawienie": {
      name: "Objawienie",
      opis: "Pewnego dnia, duchy przemówiły do mnie. Odeszły dopiero, gdy im pomogłem.",
      give: { osiągnięcia: "Przyjaciel Przodków</br>" }
    },
    "Szpiegostwo wynalazków": {
      name: "Szpiegostwo wynalazków",
      opis: "Miałem minuty na zapamiętanie planów maszyn i ich przerysowanie.",
      give: { ekstraSprzet: 1 } //@TODO ekstrasprzęt do dorobienia
    },
    "Zdrada": {
      name: "Zdrada",
      opis: "Porzuciłem przyjaciół w czarnej godzinie dla osobistych korzyści. Ci, którzy przeżyli, nie zapomną mi tego.",
      give: { bonus: 1 }
    },
    "Człowiek bez tajemnic": {
      name: "Człowiek bez tajemnic",
      opis: "Nie mam niczego takiego, co mógłbym uznać za jakiś wielki sekret.",
      give: {} // funkcja wybierająca najniższą cechę i dodająca +1 lub pozwalająca wybrać, jeśli kilka ma tę statystykę  osiągnięcia: "+1 Cecha, którą mam naniżą (gdy kilka, wybieram jedną z nich)" 
    },
    "Tajemnicze morderstwo": {
      name: "Tajemnicze morderstwo",
      opis: "Z pozoru prosta sprawa okazała się częścią wielkiej i niebezpiecznej gry.",
      give: { wola: 1 }
    },
    "Gorący romans": {
      name: "Gorący romans",
      opis: "Wpadłem w sidła niebezpiecznej miłości.  ",
      give: { osiągnięcia: "Przychylność dowolnego klanu z podręcznika.</br>" }
    },
    "Mistyczne bractwo": {
      name: "Mistyczne bractwo",
      opis: "Brałem udział w tajemnych rytuałach i dyskutowałem o teoriach okultyzmu i technomagii.",
      give: { osiągnięcia: "Adept okultystycznych sekretów.</br>" }
    },
    "Fałszywa tożsamość": {
      name: "Fałszywa tożsamość",
      opis: "Przez wiele lat musiałem udawać kogoś, kim nie byłem.",
      give: { przewagi: 3 } //@TODO przewagi do dodania do osiągnięć
    },
    "Zuchwała kradzież": {
      name: "Zuchwała kradzież",
      opis: ". Przełamałem zabezpieczenia, by wykraść Unitom to, czego potrzebowałem. Prawowity właściciel do dzisiaj bada, kto dokonał kradzieży.",
      give: { tempBonus: 3 }
    },
    "Nie brać jeńców": {
      name: "Nie brać jeńców",
      opis: "Fala okrucieństw, jakich dopuścił się mój oddział przynosi mi koszmary senne.",
      give: { walka: 1, splugawienie: 1 }
    },
    "Opętany": {
      name: "Opętany",
      opis: "Na jakiś czas mym ciałem zawładnął upiór. Odszedł, ale skalał moje ciało Ciemnością.",
      give: { ciemność: {} } // tutaj losowanie z podręcznika
    }
  }
};
//obiekt z wynikami rzutów kości dla historii, wszystkie frakcie, wszystkie rzuty
const history = {
  clan: {
    soldaci: {
      2: { ...historyTable.clan[`Wojna`] },
      3: { ...historyTable.clan[`Wojna`] },
      4: { ...historyTable.clan[`Objawienie artysty`] },
      5: { ...historyTable.clan[`Oskarżenia o herezję`] },
      6: { ...historyTable.clan[`Upiór`] },
      7: { ...historyTable.clan[`Eksperymenty alchemiczne`] },
      8: { ...historyTable.clan[`Porywczy przełożony`] },
      9: { ...historyTable.clan[`Porywczy przełożony`] },
      10: { ...historyTable.clan[`Bestia w ludzkiej skórze`] },
      11: { ...historyTable.clan[`Przesłuchanie`] },
      12: { ...historyTable.clan[`Przesłuchanie`] },
      13: { ...historyTable.clan[`Rytuał traw`] },
      14: { ...historyTable.clan[`Zawody`] },
      15: { ...historyTable.clan[`Twarde negocjacje`] },
      16: { ...historyTable.clan[`Pomocnik medyka`] },
      17: { ...historyTable.clan[`Pojedynek`] },
      18: { ...historyTable.clan[`Mistrz ostrza`] },
      19: { ...historyTable.clan[`Mistrz ostrza`] },
      20: { ...historyTable.clan[`Na szczycie władzy`] }
    },
    hanza: {
      2: { ...historyTable.clan[`Beztroskie dzieciństwo`] },
      3: { ...historyTable.clan[`Beztroskie dzieciństwo`] },
      4: { ...historyTable.clan[`Wojna`] },
      5: { ...historyTable.clan[`Objawienie artysty`] },
      6: { ...historyTable.clan[`Eksperymenty alchemiczne`] },
      7: { ...historyTable.clan[`Weryfikacja umów`] },
      8: { ...historyTable.clan[`Weryfikacja umów`] },
      9: { ...historyTable.clan[`Porywczy przełożony`] },
      10: { ...historyTable.clan[`Przesłuchanie`] },
      11: { ...historyTable.clan[`Twarde negocjacje`] },
      12: { ...historyTable.clan[`Twarde negocjacje`] },
      13: { ...historyTable.clan[`Zakapiory`] },
      14: { ...historyTable.clan[`Zdrada`] },
      15: { ...historyTable.clan[`Zdrada`] },
      16: { ...historyTable.clan[`Pojedynek`] },
      17: { ...historyTable.clan[`Pojedynek`] },
      18: { ...historyTable.clan[`Mistrz ostrza`] },
      19: { ...historyTable.clan[`Na szczycie władzy`] },
      20: { ...historyTable.clan[`Na szczycie władzy`] }
    },
    mechanisci: {
      2: { ...historyTable.clan[`Beztroskie dzieciństwo`] },
      3: { ...historyTable.clan[`Wojna`] },
      4: { ...historyTable.clan[`Oskarżenia o herezję`] },
      5: { ...historyTable.clan[`Eksperymenty alchemiczne`] },
      6: { ...historyTable.clan[`Eksperymenty alchemiczne`] },
      7: { ...historyTable.clan[`Weryfikacja umów`] },
      8: { ...historyTable.clan[`Bestia w ludzkiej skórze`] },
      9: { ...historyTable.clan[`Szkoła`] },
      10: { ...historyTable.clan[`Szkoła`] },
      11: { ...historyTable.clan[`Zawody`] },
      12: { ...historyTable.clan[`Zawody`] },
      13: { ...historyTable.clan[`Twarde negocjacje`] },
      14: { ...historyTable.clan[`Pomocnik medyka`] },
      15: { ...historyTable.clan[`Pomocnik medyka`] },
      16: { ...historyTable.clan[`Zakapiory`] },
      17: { ...historyTable.clan[`Zdrada`] },
      18: { ...historyTable.clan[`Uczeń czarnoksiężnika`] },
      19: { ...historyTable.clan[`Mistrz ostrza`] },
      20: { ...historyTable.clan[`Na szczycie władzy`] }
    },
    rytualisci: {
      2: { ...historyTable.clan[`Beztroskie dzieciństwo`] },
      3: { ...historyTable.clan[`Wojna`] },
      4: { ...historyTable.clan[`Objawienie artysty`] },
      5: { ...historyTable.clan[`Oskarżenia o herezję`] },
      6: { ...historyTable.clan[`Upiór`] },
      7: { ...historyTable.clan[`Upiór`] },
      8: { ...historyTable.clan[`Eksperymenty alchemiczne`] },
      9: { ...historyTable.clan[`Eksperymenty alchemiczne`] },
      10: { ...historyTable.clan[`Bestia w ludzkiej skórze`] },
      11: { ...historyTable.clan[`Przesłuchanie`] },
      12: { ...historyTable.clan[`Rytuał traw`] },
      13: { ...historyTable.clan[`Szkoła`] },
      14: { ...historyTable.clan[`Zawody`] },
      15: { ...historyTable.clan[`Pomocnik medyka`] },
      16: { ...historyTable.clan[`Pomocnik medyka`] },
      17: { ...historyTable.clan[`Uczeń czarnoksiężnika`] },
      18: { ...historyTable.clan[`Uczeń czarnoksiężnika`] },
      19: { ...historyTable.clan[`Mistrz ostrza`] },
      20: { ...historyTable.clan[`Na szczycie władzy`] }
    }
  },
  tour: {
    soldaci: {
      2: { ...historyTable.tour[`W warsztacie Mechanistów`] },
      3: { ...historyTable.tour[`Krwawa potyczka`] },
      4: { ...historyTable.tour[`Herezja u sąsiadów`] },
      5: { ...historyTable.tour[`Podniebna bitwa`] },
      6: { ...historyTable.tour[`Cmentarzysko maszyn`] },
      7: { ...historyTable.tour[`Egzorcyzmy`] },
      8: { ...historyTable.tour[`Wyprawa po wierzchowce`] },
      9: { ...historyTable.tour[`Oblężenie`] },
      10: { ...historyTable.tour[`Odpowiedzialne zadanie`] },
      11: { ...historyTable.tour[`Oczyścić teren`] },
      12: { ...historyTable.tour[`Wyprawa do gniazda`] },
      13: { ...historyTable.tour[`Obława na splugawionych`] },
      14: { ...historyTable.tour[`Szkolenie szturmowców`] },
      15: { ...historyTable.tour[`Wypad do katedry`] },
      16: { ...historyTable.tour[`Żarowy przemyt`] },
      17: { ...historyTable.tour[`Ucieczka z kazamatów`] },
      18: { ...historyTable.tour[`Pokrewna dusza`] },
      19: { ...historyTable.tour[`Krwawe łowy`] },
      20: { ...historyTable.tour[`Nauki u szalonego konstruktora`] }
    },
    hanza: {
      2: { ...historyTable.tour[`W warsztacie Mechanistów`] },
      3: { ...historyTable.tour[`W warsztacie Mechanistów`] },
      4: { ...historyTable.tour[`Krwawa potyczka`] },
      5: { ...historyTable.tour[`Podniebna bitwa`] },
      6: { ...historyTable.tour[`Podniebna bitwa`] },
      7: { ...historyTable.tour[`Cmentarzysko maszyn`] },
      8: { ...historyTable.tour[`Egzorcyzmy`] },
      9: { ...historyTable.tour[`Odpowiedzialne zadanie`] },
      10: { ...historyTable.tour[`Oczyścić teren`] },
      11: { ...historyTable.tour[`Obława na splugawionych`] },
      12: { ...historyTable.tour[`Szkolenie szturmowców`] },
      13: { ...historyTable.tour[`Na dworze seniora`] },
      14: { ...historyTable.tour[`Na dworze seniora`] },
      15: { ...historyTable.tour[`Wypad do katedry`] },
      16: { ...historyTable.tour[`Żarowy przemyt`] },
      17: { ...historyTable.tour[`Ucieczka z kazamatów`] },
      18: { ...historyTable.tour[`Pokrewna dusza`] },
      19: { ...historyTable.tour[`Krwawe łowy`] },
      20: { ...historyTable.tour[`Piekło na ziemi`] }
    },
    mechanisci: {
      2: { ...historyTable.tour[`W warsztacie Mechanistów`] },
      3: { ...historyTable.tour[`W warsztacie Mechanistów`] },
      4: { ...historyTable.tour[`Herezja u sąsiadów`] },
      5: { ...historyTable.tour[`Herezja u sąsiadów`] },
      6: { ...historyTable.tour[`Podniebna bitwa`] },
      7: { ...historyTable.tour[`Cmentarzysko maszyn`] },
      8: { ...historyTable.tour[`Cmentarzysko maszyn`] },
      9: { ...historyTable.tour[`Oblężenie`] },
      10: { ...historyTable.tour[`Odpowiedzialne zadanie`] },
      11: { ...historyTable.tour[`Oczyścić teren`] },
      12: { ...historyTable.tour[`Szkolenie szturmowców`] },
      13: { ...historyTable.tour[`Na dworze seniora`] },
      14: { ...historyTable.tour[`Wypad do katedry`] },
      15: { ...historyTable.tour[`Żarowy przemyt`] },
      16: { ...historyTable.tour[`Pokrewna dusza`] },
      17: { ...historyTable.tour[`Krwawe łowy`] },
      18: { ...historyTable.tour[`Krwawe łowy`] },
      19: { ...historyTable.tour[`Nauki u szalonego konstruktora`] },
      20: { ...historyTable.tour[`Piekło na ziemi`] }
    },
    rytualisci: {
      2: { ...historyTable.tour[`W warsztacie Mechanistów`] },
      3: { ...historyTable.tour[`Krwawa potyczka`] },
      4: { ...historyTable.tour[`Herezja u sąsiadów`] },
      5: { ...historyTable.tour[`Herezja u sąsiadów`] },
      6: { ...historyTable.tour[`Egzorcyzmy`] },
      7: { ...historyTable.tour[`Wyprawa po wierzchowce`] },
      8: { ...historyTable.tour[`Oblężenie`] },
      9: { ...historyTable.tour[`Odpowiedzialne zadanie`] },
      10: { ...historyTable.tour[`Oczyścić teren`] },
      11: { ...historyTable.tour[`Wyprawa do gniazda`] },
      12: { ...historyTable.tour[`Obława na splugawionych`] },
      13: { ...historyTable.tour[`Obława na splugawionych`] },
      14: { ...historyTable.tour[`Szkolenie szturmowców`] },
      15: { ...historyTable.tour[`Na dworze seniora`] },
      16: { ...historyTable.tour[`Wypad do katedry`] },
      17: { ...historyTable.tour[`Ucieczka z kazamatów`] },
      18: { ...historyTable.tour[`Pokrewna dusza`] },
      19: { ...historyTable.tour[`Krwawe łowy`] },
      20: { ...historyTable.tour[`Piekło na ziemi`] }
    }
  },
  secr: {
    soldaci: {
      2: { ...historyTable.secr[`Przed obliczem justycjariusza`] },
      3: { ...historyTable.secr[`Pakt ze splugawionym`] },
      4: { ...historyTable.secr[`Pakt ze splugawionym`] },
      5: { ...historyTable.secr[`W kajdanach`] },
      6: { ...historyTable.secr[`Jedyny ocalały`] },
      7: { ...historyTable.secr[`Jedyny ocalały`] },
      8: { ...historyTable.secr[`Objawienie`] },
      9: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      10: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      11: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      12: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      13: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      14: { ...historyTable.secr[`Tajemnicze morderstwo`] },
      15: { ...historyTable.secr[`Gorący romans`] },
      16: { ...historyTable.secr[`Gorący romans`] },
      17: { ...historyTable.secr[`Fałszywa tożsamość`] },
      18: { ...historyTable.secr[`Zuchwała kradzież`] },
      19: { ...historyTable.secr[`Nie brać jeńców`] },
      20: { ...historyTable.secr[`Opętany`] }
    },
    hanza: {
      2: { ...historyTable.secr[`Przed obliczem justycjariusza`] },
      3: { ...historyTable.secr[`W kajdanach`] },
      4: { ...historyTable.secr[`W kajdanach`] },
      5: { ...historyTable.secr[`Jedyny ocalały`] },
      6: { ...historyTable.secr[`Wielki przekręt`] },
      7: { ...historyTable.secr[`Szpiegostwo wynalazków`] },
      8: { ...historyTable.secr[`Zdrada`] },
      9: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      10: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      11: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      12: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      13: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      14: { ...historyTable.secr[`Tajemnicze morderstwo`] },
      15: { ...historyTable.secr[`Gorący romans`] },
      16: { ...historyTable.secr[`Gorący romans`] },
      17: { ...historyTable.secr[`Mistyczne bractwo`] },
      18: { ...historyTable.secr[`Fałszywa tożsamość`] },
      19: { ...historyTable.secr[`Zuchwała kradzież`] },
      20: { ...historyTable.secr[`Opętany`] }
    },
    mechanisci: {
      2: { ...historyTable.secr[`Przed obliczem justycjariusza`] },
      3: { ...historyTable.secr[`W kajdanach`] },
      4: { ...historyTable.secr[`Jedyny ocalały`] },
      5: { ...historyTable.secr[`Wielki przekręt`] },
      6: { ...historyTable.secr[`Szpiegostwo wynalazków`] },
      7: { ...historyTable.secr[`Szpiegostwo wynalazków`] },
      8: { ...historyTable.secr[`Szpiegostwo wynalazków`] },
      9: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      10: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      11: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      12: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      13: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      14: { ...historyTable.secr[`Gorący romans`] },
      15: { ...historyTable.secr[`Mistyczne bractwo`] },
      16: { ...historyTable.secr[`Fałszywa tożsamość`] },
      17: { ...historyTable.secr[`Zuchwała kradzież`] },
      18: { ...historyTable.secr[`Zuchwała kradzież`] },
      19: { ...historyTable.secr[`Nie brać jeńców`] },
      20: { ...historyTable.secr[`Opętany`] }
    },
    rytualisci: {
      2: { ...historyTable.secr[`Przed obliczem justycjariusza`] },
      3: { ...historyTable.secr[`Pakt ze splugawionym`] },
      4: { ...historyTable.secr[`Pakt ze splugawionym`] },
      5: { ...historyTable.secr[`Jedyny ocalały`] },
      6: { ...historyTable.secr[`Objawienie`] },
      7: { ...historyTable.secr[`Objawienie`] },
      8: { ...historyTable.secr[`Zdrada`] },
      9: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      10: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      11: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      12: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      13: { ...historyTable.secr[`Człowiek bez tajemnic`] },
      14: { ...historyTable.secr[`Tajemnicze morderstwo`] },
      15: { ...historyTable.secr[`Mistyczne bractwo`] },
      16: { ...historyTable.secr[`Mistyczne bractwo`] },
      17: { ...historyTable.secr[`Fałszywa tożsamość`] },
      18: { ...historyTable.secr[`Zuchwała kradzież`] },
      19: { ...historyTable.secr[`Nie brać jeńców`] },
      20: { ...historyTable.secr[`Opętany`] }
    }
  }

}
const darkGifts = {
  1: {
    name: 'Słodycz tajemnicy',
    info: 'Spoglądając innej postaci w oczy, udanym spornym testem Okultyzmu (mam w nim ułatwienie) poznaję lęk lub sekret swego rozmówcy. Późniejsze użycie sekretu w interakcji z tą osobą da mi +1 sukces.',
    times: 'one',
  },
  2: {
    name: 'Spirala nienawiści',
    info: 'Gdy jestem wzburzony, przysługuje mi dodatkowy darmowy atak w swojej kolejce we wszystkich konfliktach.',
    times: 'many',
  },
  3: {
    name: 'Cyrograf ognistego serca',
    info: 'Sprzedałem serce demonom. Gdy powinienem umrzeć w ciągu tygodnia odradzam się, wychodząc z najbliższych płomieni. Każda kolejna śmierć daje mi 50% szansy  na odrodzenie.',
    times: 'one',
  },
  4: {
    name: 'Ślepia',
    info: 'Oczy lśnią mi diabelskim blaskiem, żarząc się odbiciem ogni piekielnych. Widzę w półmroku i całkowitych ciemnościach. Ułatwienie w akcjach zastraszania.',
    times: 'many',
  },
  5: {
    name: 'Szkarłatny karaluch',
    info: 'Mogę poruszać się po wszystkich płaszczyznach (np. po ścianach lub suficie). Ułatwienie w działaniach, w których może mi to pomóc np. akcja uniku w walce, akcja przemieszczania się, wspinaczka, zastanawianie pułapki...',
    times: 'many',
  },
  6: {
    name: 'Szepty paranoi',
    info: 'Słyszę głosy w głowie, które ostrzegają mnie przed niebezpieczeństwem. +1 sukces w trakcie ustalania kolejności działań. Nie można mnie zaskoczyć.  Nigdy.',
    times: 'many',
  },
  7: {
    name: 'Nożycoręki',
    info: 'W ciągu akcji moje dłonie zamieniają się w metalowe ostrza i haki. +1 obrażeń, ignorują Pancerz (ale nie mistyczny).Ułatwienie w akcji ataków w walce.',
    times: 'one',
  },
  8: {
    name: 'Zaklinacz ogarów',
    info: 'Udanym testem (2) Okultyzmu Przywołuję dwa piekielne ogary (s. xxx) a za każde przebicie zwiększam +1 jedną z ich Cech. Demony będą mi posłuszne do końca sceny, po czym odejdą w Pomrok.',
    times: 'one',
  },
  9: {
    name: 'Moloch',
    info: 'Wykonuję z ułatwieniem dowolną akcje opierające się na Cechach fizycznych.',
    times: 'one',
  },
  10: {
    name: 'Diabelski głos',
    info: 'Wykonuję z ułatwieniem dowolną akcje interakcji społecznej.',
    times: 'one',
  },
  11: {
    name: 'Skok przez Cienie',
    info: 'Testem (1) okultyzmu błyskawicznie wskakuję w Pomrok i wyskakuję do 5m dalej za każde uzyskane przebicie, niezależnie od przeszkód po drodze. Otrzymuję +1 sukces do akcji ruchu i pierwszej akcji walki. Nieudany test blokuje skok do końca sceny.',
    times: 'many',
  },
  12: {
    name: 'Złodziej dusz',
    info: 'Gdy własnoręcznie kogoś zabiję i naznaczę go pocałunkiem, kradnę jego duszę. Od tej chwili w kilka minut potrafię przybrać wygląd i głos posiadacza ostatniej duszy wraz z jej Talentami.',
    times: 'one',
  },
  13: {
    name: 'Szyderstwo mięsa',
    info: 'Wyklinaniem i szydzeniem z drugiej osoby oraz akcją z udanym testem spornym Charyzmy przeciw Krzepie ofiary, wywołuję gnicie jej ciała. Zadają one 3 obrażeń + przebicia z ataku –jej Mistyczny pancerz.',
    times: 'one',
  },
  14: {
    name: 'Bestia Czarnej Spirali',
    info: 'Stan zagubienie pozwala mi dodatkowo przemienić się w potwora zwanego stalokostnym homunkulusem (s.xxx), zyskując jego Talenty i Cechy, które są wyższe od moich. Powrót do zwykłej postaci zajmuje 1 akcję.',
    times: 'one',
  },
}

const archetypeToChoose = {
  siepacz: {
    walka: 3,
    parkour: 2,
    krzepa: 3,
    charyzma: 1,
    zimna: 1,
    okultyzm: 1,
    czujnosc: 1,
    wola: 1,
    witalnosc: 2,
  },
  egzorcysta: {
    parkour: 1,
    charyzma: 2,
    zimna: 3,
    status: 1,
    okultyzm: 3,
    wiedza: 2,
    czujnosc: 1,
    witalnosc: 2,
    wola: 1,
  },
  kronikarz: {
    walka: 1,
    charyzma: 3,
    okultyzm: 1,
    parkour: 2,
    zimna: 1,
    wiedza: 3,
    witalnosc: 2,
    status: 2,
    wola: 1,
  },
  przepatrywacz: {
    walka: 2,
    okultyzm: 1,
    parkour: 2,
    zimna: 1,
    witalnosc: 2,
    krzepa: 3,
    status: 1,
    czujnosc: 2,
    wola: 1,
  },
  rzecznik: {
    walka: 1,
    charyzma: 3,
    parkour: 1,
    zimna: 2,
    wiedza: 1,
    status: 3,
    czujnosc: 2,
    wola: 2,
  },
  sniacy: {
    charyzma: 2,
    okultyzm: 3,
    zimna: 1,
    wiedza: 2,
    witalnosc: 1,
    krzepa: 1,
    status: 3,
    czujnosc: 1,
    wola: 2,
    drzewo: -1,
  },
  szabrownik: {
    walka: 1,
    parkour: 3,
    zimna: 2,
    wiedza: 1,
    witalnosc: 2,
    krzepa: 1,
    status: 1,
    czujnosc: 3,
    wola: 1,
  },
  wiedzmiarz: {
    charyzma: 2,
    okultyzm: 3,
    zimna: 2,
    wiedza: 1,
    witalnosc: 1,
    krzepa: 1,
    status: 1,
    czujnosc: 3,
    wla: 2,
    drzewo: -1,
  },
  zerca: {
    walka: 2,
    okultyzm: 2,
    parkour: 3,
    zimna: 3,
    wiedza: 1,
    witalnosc: 2,
    krzepa: 1,
    czujnosc: 1,
    wola: 1,
  },
}

const heroNames = {
  soldaci: {
    boy: {
      1: "Bartosz",
      2: "Bazyl",
      3: "Borys",
      4: "Dymitr",
      5: "Fiodor",
      6: "Gabor",
      7: "Igor",
      8: "Ivan",
      9: "Lech",
      10: "Leon",
      11: "Mieszko",
      12: "Miłosz",
      13: "Siergiej",
      14: "Wasyl",
      15: "Wladimir",
    },
    girl: {
      1: "Agnieszka",
      2: "Dziewanna",
      3: "Grażyna",
      4: "Kachna",
      5: "Maja",
      6: "Malina",
      7: "Malwina",
      8: "Milena",
      9: "Natasza",
      10: "Olga",
      11: "Róża",
      12: "Tatiana",
      13: "Tola",
      14: "Wanda",
      15: "Zuzanna",
    },
  },
  hanza: {
    boy: {
      1: 'Alan',
      2: 'Ardal',
      3: 'Brendan',
      4: 'Brian',
      5: 'Cahir',
      6: 'Colm',
      7: 'Cormac',
      8: 'Daragh',
      9: 'Desmond',
      10: 'Devin',
      11: 'Edan',
      12: 'Fergal',
      13: 'Fergus',
      14: 'Fion',
      15: 'Gerald',
      16: 'Goban',
      17: 'Ivor',
      18: 'Kane',
      19: 'Kevin',
      20: 'Murdoch',
      21: 'Nevan',
      22: 'Oscar',
      23: 'Patrick',
      24: 'Redmund',
      25: 'Rowan',
      26: 'Ryan',
      27: 'Sean',
      28: 'Shane',
      29: 'Toal',      
    },
    girl: {
      1: 'Ailis',
      2: 'Aislin',
      3: 'Caitlin',
      4: 'Casley',
      5: 'Delma',
      6: 'Elva',
      7: 'Enya',
      8: 'Erin',
      9: 'Etna',
      10: 'Finola',
      11: 'Fiona',
      12: 'Ita',
      13: 'Muriel',
      14: 'Neve',
      15: 'Nola',
      16: 'Sheila',
      17: 'Shevon',
      18: 'Sorcha',
      19: 'Talulla',
    },
  },
  mechanisci: {
    boy: {
      1: 'Albrecht', 
      2: 'Alfred', 
      3: 'Detlef', 
      4: 'Dieter', 
      5: 'Dietrich', 
      6: 'Erich', 
      7: 'Ernst', 
      8: 'Erwin', 
      9: 'Franz', 
      10: 'Fritz', 
      11: 'Gerhard', 
      12: 'Gottfried', 
      13: 'Gunter', 
      14: 'Gustav', 
      15: 'Hans', 
      16: 'Heinz', 
      17: 'Johann', 
      18: 'Jürgen', 
      19: 'Klaus', 
      20: 'Konrad', 
      21: 'Lothar', 
      22: 'Manfred', 
      23: 'Olaf', 
      24: 'Otto', 
      25: 'Raimund', 
      26: 'Rupert', 
      27: 'Siegdried', 
      28: 'Ulrich', 
      29: 'Urs', 
      30: 'Wolfgang', 
    },
    girl: {
      1: 'Agnes', 
      2: 'Anika', 
      3: 'Bertha', 
      4: 'Brigitta', 
      5: 'Brünhilda', 
      6: 'Dagmar', 
      7: 'Elise', 
      8: 'Elma', 
      9: 'Elsa', 
      10: 'Frida', 
      11: 'Gisa', 
      12: 'Gitta', 
      13: 'Greta', 
      14: 'Gunda', 
      15: 'Hega', 
      16: 'Hilda', 
      17: 'Ida', 
      18: 'Ilsa', 
      19: 'Inga', 
      20: 'Irma', 
      21: 'Jutta', 
      22: 'Kinga', 
      23: 'Klara', 
      24: 'Lisa', 
      25: 'Mitzi', 
      26: 'Nora', 
      27: 'Susi', 
      28: 'Truda', 
      29: 'Uta',
    },
  },
  rytualisci: {
    boy: {
      1: 'Agam',
      2: 'Amir',
      3: 'Arioch',
      4: 'Aron',
      5: 'Dagon',
      6: 'Eliasz',
      7: 'Enoch',
      8: 'Gabriel',
      9: 'Harut',
      10: 'Keshet',
      11: 'Kyle',
      12: 'Leib',
      13: 'Melech',
      14: 'Moran',
      15: 'Mordechai',
      16: 'Nahor',
      17: 'Natan',
      18: 'Peleg',
      19: 'Remiel',
      20: 'Saul',
      21: 'Serafin',
      22: 'Simon',
      23: 'Sol',
      24: 'Uriel',
      25: 'Yudel',
      26: 'Zion',
    },
    girl: {
      1: 'Amira', 
      2: 'Avia', 
      3: 'Ayla', 
      4: 'Carmel', 
      5: 'Daria', 
      6: 'Deborah', 
      7: 'Dinah', 
      8: 'Kasandra', 
      9: 'Keren', 
      10: 'Lihi', 
      11: 'Miriam', 
      12: 'Naomi', 
      13: 'Nava', 
      14: 'Nissa', 
      15: 'Rachel', 
      16: 'Raisa', 
      17: 'Rebeka', 
      18: 'Shani', 
      19: 'Zelda', 
    },
  }, 
}

const heroClan = {
  soldaci: {
    1: "Bestiarze Srogieja",
    2: "Czarny Sztandar",
    3: "Czatownicy",
    4: "Dobosze",
    5: "Duchy Ruin",
    6: "Fortyfikatorzy",
    7: "Gwardianie",
    8: "Grasanci Gruzowisk",
    9: "Iskrobladzi",
    10: "Krwawa Chorągiew",
    11: "Kolekcjonerzy Szram",
    12: "Kompania Szturmowa",
    13: "Krąg Ogniokrwistych",
    14: "Legion Burz",
    15: "Leśny Hufiec",
    16: "Lodowe Kły",
    17: "Lotniarze Iglicy",
    18: "Łańcuchowcy",
    19: "Łobuzy Pogracznia",
    20: "Maruderzy Jezkova",
    21: "Pawężnicy",
    22: "Pieśniarze Trucheł",
    23: "Piewcy Hymnów",
    24: "Podwójne Ostrza",
    25: "Podziemni Drapieżcy",
    26: "Poskramiacze",
    27: "Powietrzni Łupieżcy",
    28: "Pustynna Sfora",
    29: "Rębacze Kości",
    30: "Skórozdziercy",
    31: "Słoneczne Włócznie",
    32: "Skrzydlaci Lansjerzy",
    33: "Staloworęcy",
    34: "Stepowi Harcownicy",
    35: "Najemne Rękawice",
    36: "Nieugięta Gwardia",
    37: "Nocni Łowcy",
    38: "Ogary Tuneli",
    39: "Ogniowy Bastion",
    40: "Pancerny Batalion",
    41: "Szable Zmarzliny",
    42: "Szarpany Proporzec",
    43: "Szpony Obręczy",
    44: "Tancerze Krwi",
    45: "Tyraliera",
    46: "Wiatroskrzydli",
    47: "Wypruwacze Implantów",
    48: "Zębate Tarcze",
    49: "Znachorzy Blizn",
    50: "Żelaznobocy",
  },
  hanza: {
    1: 'Areth', 
    2: 'Banach', 
    3: 'Białopióry', 
    4: 'Cadrach', 
    5: 'Capadocian', 
    6: 'Cardogan', 
    7: 'z Chmurnej Przystani', 
    8: 'z Czarnozamcza', 
    9: 'Dragan', 
    10: 'Dwukwiat', 
    11: 'Finn', 
    12: 'Flaganon', 
    13: 'Fodlach', 
    14: 'Geneth', 
    15: 'Gnieworodny', 
    16: 'Graffton', 
    17: 'Grawermiecz', 
    18: 'Herboróża', 
    19: 'Herboskóry', 
    20: 'Iluin', 
    21: 'Uther', 
    22: 'z Lodoszerni', 
    23: 'Muldor', 
    24: 'Maelstorm', 
    25: 'Włodarz', 
    26: 'Mor', 
    27: 'Nemeth', 
    28: 'Ollogath', 
    29: 'z Podzamcza', 
    30: 'z Powietrznej Fortecy', 
    31: 'Prawosłowa', 
    32: 'z Przesmyku Kirysów', 
    33: 'z Rubinowego Dworu', 
    34: 'Skarbidor', 
    35: 'ze Skarbnicy', 
    36: 'ze Słonecznej Cytadeli', 
    37: 'Smokobójca', 
    38: 'Srebrniarz', 
    39: 'ze Srebrnowieży', 
    40: 'Strażnik Insygni', 
    41: 'Sygil', 
    42: 'Szafarz', 
    43: 'Telmeth', 
    44: 'Turgmor', 
    45: 'z Twierdzy Gnazz', 
    46: 'Senjak', 
    47: 'Malfoy', 
    48: 'Zaprzysiężca', 
    49: 'ze Złotych Bulwarów', 
    50: 'Żarokrwisty',     
  },
  mechanisci: {
    1: 'Akademia Rzemiosła', 
    2: 'Architekci Mechanoidów', 
    3: 'Archiwiści Projektów', 
    4: 'Arsenał Szturmowy', 
    5: 'Diagnostycy Toksyn', 
    6: 'Druciarze', 
    7: 'Dyskomanci', 
    8: 'Grawerzy Żaroformuł', 
    9: 'Impregnatorzy', 
    10: 'Kartoteka Technokracji', 
    11: 'Kreślarze Schematów', 
    12: 'Klasyfikatorzy Znalezisk', 
    13: 'Konwertyści Mikstur', 
    14: 'Korpus Górniczy', 
    15: 'Kruszcowa Hałda', 
    16: 'Kryształowe Laboratorium', 
    17: 'Kursanci Rozpłata', 
    18: 'Kuźnia Staloformy', 
    19: 'Magazyn Surowców', 
    20: 'Magistranci Alchemii', 
    21: 'Magmowy Szyb', 
    22: 'Manufaktura Żarosprzętu', 
    23: 'Metalurdzy', 
    24: 'Mnemotycy', 
    25: 'Odlewnia Matryc', 
    26: 'Ogniomistrze', 
    27: 'Pasaż Znalezisk', 
    28: 'Pionierzy Machin', 
    29: 'Podmorski Warsztat', 
    30: 'Podniebna Stocznia', 
    31: 'Powietrzna Placówka', 
    32: 'Przetwórcy Metali', 
    33: 'Rdzawe Dźwigary ', 
    34: 'Regulatorzy', 
    35: 'Rekonstruktorzy Maszyn', 
    36: 'Rupieciarze', 
    37: 'Scalone Moduły', 
    38: 'Segment Toksyniarzy', 
    39: 'Składnica Szabrownicza', 
    40: ' Sprężynowe Przeguby', 
    41: 'Szklane Obserwatorium', 
    42: 'Szlifierze', 
    43: 'Szynogeci', 
    44: 'Techmistycy Struktury', 
    45: 'Technoklan Dyspersji', 
    46: 'Warowna Drukarnia', 
    47: 'Wypalane Tafle', 
    48: 'Wytwórcy Protez', 
    49: 'Wyżeracze Stali', 
    50: 'Złomiarze', 
  },
  rytualisci: {
    1: 'Alchemiści', 
    2: 'Balsamiści', 
    3: 'Bezimienni', 
    4: 'Bractwo Cieniomasek', 
    5: 'Cieniogeci', 
    6: 'Derwisze', 
    7: 'Dom Wróżb', 
    8: 'Dyscyplinariusze', 
    9: 'Echo Grimuarów', 
    10: 'Egzekutorzy Grzechów', 
    11: 'Geoci', 
    12: 'Grawerzy Klątw', 
    13: 'Inkrustratorzy zaklęć', 
    14: 'Kartomanci', 
    15: 'Katedra uroków', 
    16: 'Konsylium Techgetów', 
    17: 'Konwikt Wstęgi', 
    18: 'Kopiści Wspomnień', 
    19: 'Krąg Potępionych', 
    20: 'Kreślarze ciał', 
    21: 'Księżycowi Kajdaniarze', 
    22: 'Kurhan Nawiedzeń', 
    23: 'Łamacze Uroków', 
    24: 'Odtwórcy Mantrocyklu', 
    25: 'Mantrycy', 
    26: 'Obserwatorzy', 
    27: 'Oddział Leviego', 
    28: 'Pielgrzymi Czarnej Spirali', 
    29: 'Powiernicy imion', 
    30: 'Protektorzy pieczęci', 
    31: 'Rotarzy', 
    32: 'Rozpruwacze Kurtyny', 
    33: 'Rytownicy Formuł', 
    34: 'Scholarzy', 
    35: 'Skryptorzy mitów', 
    36: 'Studniarze', 
    37: 'Symboliści', 
    38: 'Szpitalnicy', 
    39: 'Tkacze wersetów', 
    40: 'Tropiciele Cieni', 
    41: 'Uzdrowiciele Dusz', 
    42: 'Warzelnicy eliksirów', 
    43: 'Wirujący w ciszy', 
    44: 'Wygrzebańcy', 
    45: 'Wypalacze run', 
    46: 'Zaklinacze Żaru', 
    47: 'Zjadacze Sekretów', 
    48: 'Znachorzy Mieczy', 
    49: 'Żałobnicy', 
    50: 'Żarowa Dzwonnica',     
  },
}
